1
pandangie/DevNube-Bootcamp-1---Exerc-cios pull request #1
Opened 2023-02-13 19:21 UTC by pandangie

2023-02-13 20:47 UTC, dvnube requested changes
review ao vivo

2023-02-13 23:58 UTC, dvnube approved these changes
só remover a condição redundante, mas tá legal!
boa.

2023-02-13 23:58 UTC, dvnube commented on Exercício 1
> +Se a luz estiver acesa então
essa condição é desnecessária, tendo em vista que a luz com certeza estará acesa
não existe nenhum caminho no seu algoritmo onde seja possível a luz estar apagada
logo, essa condição é redundante
remova-a

2023-02-13 23:59 UTC, dvnube commented on Exercício 1
> +Se a luz estiver acesa então
depois que vc fizer a alteração, pode clicar em "merge pull request"

2023-02-16 11:21 UTC, pandangie commented on Exercício 1
> +Se a luz estiver acesa então
Beleza!!!

2023-02-16 11:24 UTC, merged